### ISSUE TITLE
tabbable breaks when processing an element with a "scope" attribute

### ISSUE THREAD

**Issue by les-lim** [focus-trap/tabbable#832]
I have a situation where a TH element has both `scope="col"` and `tabindex="0"` attributes, which is causing Tabbable to break with "Cannot read properties of undefined (reading 'forEach').

> index.js:425 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
>     at e (index.js:425:14)
>     at index.js:429:32
>     at Array.forEach (<anonymous>)
>     at e (index.js:425:14)
>     at e.tabbable (index.js:473:10)

Tabbable appears to be evaluating `!! item.scope` as true because the attribute is present, and assumes there is a ShadowRoot to process.

**Comment by stefcameron** [comment]
@les-lim Thanks for reporting this. I will have a closer look in a few days when I've got some bandwidth.

**Comment by stefcameron** [comment]
👀

**Comment by stefcameron** [comment]
I've got a fix in https://github.com/focus-trap/tabbable/pull/847

**Comment by stefcameron** [comment]
@all-contributors add @les-lim for bug

**Comment by stefcameron** [comment]
FYI, this was fixed in tababble v6.0.1
